# Site
title:              Kiwi's Adventure
bio:                'by CryptidGrove Studio'
description:        "Kiwi's Adventure is a 3D puzzle-platformer & dungeon-crawler by Cryptid Grove Studio."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/kiwi_logo_web.png'
background:         'assets/img/kiwi_teaser_lowres.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://ies-rafael-alberti.github.io/gameoff2023/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              CryptidGroveStudio@gmail.com
twitter:            Cryptid_Grove
itchio:             cryptidgrovestudio
# facebook:           username
github-url:         IES-Rafael-Alberti/gameoff2023
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          cryptidgrovestudio
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
bluesky:            cryptidgrovestudio.bsky.social
discord:            channels/1166621054685425694


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://ies-rafael-alberti.github.io/gameoff2023/

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
